In [ ]:
# 【python讲线代】S03E01 向量和矩阵的python描述

In [2]:
import numpy as np

A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [3]:
print(A.transpose())

[1 2 3 4]


In [5]:
A_t= A[:, np.newaxis]
print(A_t)
print(A_t.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [11]:
import numpy as np
A = np.array([[1, 2, 3], [0.4, -4, 2]])
print(A)
print(A.shape)

[[ 1.   2.   3. ]
 [ 0.4 -4.   2. ]]
(2, 3)
